jms_security_extra:
    secure_all_services: false
    expressions: true

security:
    encoders:
        FOS\UserBundle\Model\UserInterface: sha512

    role_hierarchy:
        ROLE_MANAGER:       [ROLE_USER]
        ROLE_ADMIN: [ROLE_MANAGER, ROLE_ALLOWED_TO_SWITCH]

    providers:
        chain_provider:
            chain:
                providers: [fos_userbundle]
        fos_userbundle:
            id: fos_user.user_provider.username_email

    firewalls:
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false

        public:
            # since anonymous is allowed users will not be forced to login
            pattern:   ^/.*
            form_login:
                login_path: fos_user_security_login
                check_path: fos_user_security_check
                provider: fos_userbundle
                remember_me: true
            remember_me:
                key:         %secret%
                lifetime: 604800
                path:     /
                domain:   ~
                user_provider: fos_userbundle
            anonymous: true
            logout:          true 

        login:
            pattern:  ^/login$
            security: false